import Foundation

/// Checks a remote model's reading of a row against the arithmetic printed on the card beside it.
///
/// ## Why a model's own confidence is not enough
///
/// The real risk in handing handwriting to a multimodal model is not that it reads a 4 as a 9. It is that
/// it returns a complete, confident, plausible row of eighteen numbers that is partly invented — because
/// filling the gap is what a language model does when a cell is illegible, and it has no way to signal
/// "I guessed" that is distinguishable from "I read it". Asking for a confidence score does not fix this;
/// the confidence is generated by the same process as the guess.
///
/// So the model's answer is not trusted on its own terms. It is checked.
///
/// ## The check
///
/// A golfer writes nine strokes and then writes their sum. Those are two separate acts of handwriting in
/// two separate places on the card, and the model transcribes them separately. If the nine cells it
/// returned add up to the subtotal it *also* returned, the card has confirmed the row: an invented digit
/// would have to be matched by a correspondingly invented total, twice over, in a way that happens to be
/// arithmetically consistent. That is a far stronger guarantee than any self-reported confidence, and it
/// costs nothing but addition.
///
/// Where the local parser also managed to read a subtotal, that reading is used as a third, fully
/// independent check — a different reader entirely, on a different pass.
///
/// A row that passes is trusted enough to save. A row that fails is not rejected outright, because the
/// wrong number may well be the subtotal; it is kept at a confidence low enough that every cell in it is
/// surfaced for review and low enough that `ScoreChecksumSolver` may overwrite it.
public enum RemoteScoreAudit {

    /// One sum compared against one written subtotal.
    public struct Check: Equatable, Sendable {
        /// Which reader supplied the subtotal being checked against.
        public enum Source: String, Equatable, Sendable {
            /// The remote model transcribed the subtotal cell itself.
            case remote
            /// On-device OCR read the subtotal cell.
            case local
        }

        public var label: String
        /// The sum of the per-hole scores the model returned for this half.
        public var sum: Int
        /// The subtotal written on the card, as read by `source`.
        public var subtotal: Int
        public var source: Source

        public var passed: Bool { sum == subtotal }

        public init(label: String, sum: Int, subtotal: Int, source: Source) {
            self.label = label
            self.sum = sum
            self.subtotal = subtotal
            self.source = source
        }
    }

    public enum Verdict: Equatable, Sendable {
        /// Why no check could be run.
        public enum Unverifiable: String, Equatable, Sendable {
            /// Neither reader recovered a subtotal to check against.
            case noSubtotals
            /// The model left holes unread, so no half of the row can be summed.
            case rowIncomplete
        }

        /// Every check that could be run, passed.
        case corroborated([Check])
        /// At least one sum disagrees with a written subtotal. Carries only the failures.
        case contradicted([Check])
        case unverifiable(Unverifiable)

        public var isCorroborated: Bool {
            if case .corroborated = self { return true }
            return false
        }

        public var isContradicted: Bool {
            if case .contradicted = self { return true }
            return false
        }
    }

    /// A local subtotal is only used as a check when it was read with some conviction.
    ///
    /// Without this floor a shaky OCR read of the OUT cell would be enough to condemn a correct remote row,
    /// which gets the blame exactly backwards.
    public static let minimumLocalSubtotalConfidence = 0.6

    /// Audits one remote row.
    ///
    /// - Parameters:
    ///   - player: the row as the model returned it.
    ///   - local: the same row as the local parser read it, when it found one. Only its written subtotals
    ///     are used — its per-hole scores are the thing being second-guessed, so they are not evidence.
    ///   - holeCount: how many holes the card covers.
    public static func audit(
        player: RemoteScorecardPayload.Player,
        against local: DetectedPlayer?,
        holeCount: Int
    ) -> Verdict {
        guard holeCount > 0 else { return .unverifiable(.rowIncomplete) }

        var checks: [Check] = []

        func sum(_ holeNumbers: [Int]) -> Int? {
            var accumulated = 0
            for number in holeNumbers {
                guard let score = player.hole(number)?.playerScore else { return nil }
                accumulated += score
            }
            return accumulated
        }

        func localSubtotal(_ field: ParsedField<Int>?) -> Int? {
            guard let field, let value = field.value else { return nil }
            guard field.confidence >= minimumLocalSubtotalConfidence else { return nil }
            return value
        }

        func appendChecks(label: String, sum: Int?, remote: Int?, local: Int?) {
            guard let sum else { return }
            if let remote {
                checks.append(Check(label: label, sum: sum, subtotal: remote, source: .remote))
            }
            if let local {
                checks.append(Check(label: label, sum: sum, subtotal: local, source: .local))
            }
        }

        let frontHoles = Array(1...min(9, holeCount))
        let frontSum = sum(frontHoles)
        appendChecks(
            label: "front nine",
            sum: frontSum,
            remote: player.writtenOut,
            local: localSubtotal(local?.writtenOut)
        )

        var backSum: Int?
        if holeCount > 9 {
            backSum = sum(Array(10...holeCount))
            appendChecks(
                label: "back nine",
                sum: backSum,
                remote: player.writtenIn,
                local: localSubtotal(local?.writtenIn)
            )
        }

        // The grand total is its own check and not merely the sum of the two above: a golfer can write a
        // correct TOTAL beside an OUT they miscopied, and vice versa.
        let totalSum = sum(Array(1...holeCount))
        appendChecks(
            label: "18-hole total",
            sum: totalSum,
            remote: player.writtenTotal,
            local: localSubtotal(local?.writtenTotal)
        )

        let failures = checks.filter { !$0.passed }
        if !failures.isEmpty { return .contradicted(failures) }
        if !checks.isEmpty { return .corroborated(checks) }
        // Nothing could be checked. Distinguish the two reasons, because they call for different advice:
        // an incomplete row needs the golfer to fill gaps, a row with no subtotals simply cannot be
        // verified and has to be read over.
        return totalSum == nil ? .unverifiable(.rowIncomplete) : .unverifiable(.noSubtotals)
    }
}

/// How much a remote reading is allowed to be believed, given what the audit found.
///
/// These are ceilings, not assignments: a model that reports 0.4 on a smudged cell stays at 0.4 even when
/// the rest of its row is corroborated. The audit can only ever cap confidence, never inflate a reading
/// the model itself was unsure of.
public enum RemoteConfidencePolicy {

    /// Confirmed by the card's own arithmetic. Above `ParsedField.requiresReview`'s threshold, so a
    /// corroborated row does not nag the golfer about every cell.
    public static let corroboratedCeiling = 0.95

    /// Nothing could check it. Deliberately just below the review threshold (0.82): an unverified model
    /// reading is a suggestion the golfer confirms, not an answer.
    public static let unverifiedCeiling = 0.80

    /// The row does not add up. Below `ScoreChecksumSolver`'s overwritable threshold (0.55) as well as the
    /// review threshold, so the card's arithmetic is free to correct it and the golfer is shown all of it.
    public static let contradictedCeiling = 0.45

    public static func ceiling(for verdict: RemoteScoreAudit.Verdict) -> Double {
        switch verdict {
        case .corroborated: return corroboratedCeiling
        case .contradicted: return contradictedCeiling
        case .unverifiable: return unverifiedCeiling
        }
    }
}
